# Site settings
title: Dr
name: Nur
surname: Ozyilmaz
fulltitle: Dr Nur Ozyilmaz
appname: DrNur
email: contact@drnur.co.uk
tel: 07738 472203
address: "58 South Molton Street<br>London<br>W1K 5SL"
map: "https://goo.gl/maps/7YkcAt5nm9z"
description: Dr Nur Ozyilmaz is a consultant paediatrician with a holistic approach to children's health and wellness.
jobtitle: Paediatrician<br>&<br>Integrative Health Specialist
qualifications: CONSULTANT MD MRCPCH

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://drnur.co.uk" # the base hostname & protocol for your site
image: "https://drnur.co.uk/assets/img/nur.jpg"
facebook: "https://www.facebook.com/drnurozyilmaz/"
contactaction: "https://postman.etilia.com/d17c7c2c-5259-4318-8ce9-1c2f2fa62d35"

# production/development
mode: production
# Build settings
markdown: kramdown
permalink: /posts/:title/
